name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Android & Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.3'  # specify the Flutter version

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build WEB
        run: flutter build web --release

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: build/web/
#
#  build_ios:
#    runs-on: macOS-latest
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.13.6'
#      - name: Install CocoaPods
#        run: |
#          sudo gem install cocoapods
#          cd ios
#          pod install
#
#      - name: Install Dependencies
#        run: flutter pub get
#
#      - name: Build iOS
#        run: flutter build ios --release --no-codesign

    # Add more steps as needed, deploying to stores, etc.
